"""Turn the chosen takes into an edit decision file and a plan a person can read.

Source time is canonical. Output frames are derived here and never typed by hand, so that
changing one take shifts everything after it automatically.

The choices live in keep.json beside project.json, which is the only file a person edits:

    [
      [0, 0, "only take"],
      [5, 7, "third attempt is the complete one; 3 and 4 abandoned"],
      [14, 14, "last of five attempts; 8-13 are earlier wordings and false starts"]
    ]

Each entry is [first stretch, last stretch, why]. A range keeps its internal pauses, so
two stretches that are one sentence stay one shot. Write a reason for every entry: review
is then a scan of plan.md rather than a re-watch of the footage.

Usage: build_edit.py
"""
import json, os
from config import FPS, islands, CFG

PRE, POST, GUARD = 0.12, 0.22, 0.04   # padding in, padding out, gap left to the neighbour
MAXGAP = 0.6                          # a pause longer than this becomes a cut

I = islands()
KEEP = json.load(open('keep.json'))
# Source-time overrides, found by transcribing the finished cut: {first stretch: seconds}.
# A short false start can sit a tenth of a second before the real sentence, inside the same
# stretch of sound, where the envelope cannot see it but the ear can.
OVERRIDE = {int(k): v for k, v in CFG.get('start_override', {}).items()}


def split(a, b):
    """Break a kept range at its internal pauses, so dead air cannot ride inside a shot."""
    out, start = [], a
    for k in range(a, b):
        if I[k + 1]['s'] - I[k]['e'] > MAXGAP:
            out.append((start, k))
            start = k + 1
    return out + [(start, b)]


keep = [(x, y, why) for a, b, why in KEEP for x, y in split(a, b)]
GT = json.load(open('work/gaze_trim.json')) if os.path.exists('work/gaze_trim.json') else {}

segs, out = [], 0
for n, (a, b, why) in enumerate(keep):
    s = I[a]['s'] - PRE
    e = I[b]['e'] + POST
    if a > 0:
        s = max(s, I[a - 1]['e'] + GUARD)
    if b + 1 < len(I):
        e = min(e, I[b + 1]['s'] - GUARD)
    if a in OVERRIDE:
        s = OVERRIDE[a]
    sf, ef, fade = round(s * FPS), round(e * FPS), 0.02

    g = GT.get(str(a))
    if g:
        # Trim to frames facing the lens — but never cut more than three frames into
        # sounding speech. A clipped word is worse than a glance.
        sp_a, sp_b = round(I[a]['s'] * FPS), round(I[b]['e'] * FPS)
        sf = max(sf, min(g['start'], sp_a + 3))
        ne = max(g['end'], sp_b - 3)
        if g['end'] < ef:
            # a look-away follows this line: leave as the sound ends, because the eyes
            # drop before the head turns
            ne = max(min(g['end'], sp_b + 2), sp_b - 3)
        if ne < ef:
            if ne < sp_b:
                fade = 0.12
            ef = ne

    segs.append({'id': f's{n:02d}', 'islands': [a, b],
                 'source_start_frame': sf, 'source_end_frame': ef,
                 'output_start_frame': out, 'output_end_frame': out + (ef - sf),
                 'text': ' '.join(I[k]['text'] for k in range(a, b + 1)),
                 'reason': why, 'fade_out': fade})
    out += ef - sf

json.dump({'timebase': f'{FPS}/1', 'source': 'work/source.mov',
           'segments': segs, 'output_frames': out},
          open('lesson.edit.json', 'w'), indent=1)


def tc(f):
    return f'{int(f / FPS // 60)}:{f / FPS % 60:05.2f}'


src_len = I[-1]['e']
with open('plan.md', 'w') as p:
    p.write(f'# Edit plan\n\nGenerated by build_edit.py. Edit keep.json, not this file.\n\n'
            f'Source {tc(round(src_len * FPS))} → cut {tc(out)}. '
            f'{len(segs)} segments kept from {len(I)} stretches of speech.\n\n'
            f'| # | In the cut at | From source | Line | Why this take |\n|---|---|---|---|---|\n')
    for s in segs:
        p.write(f"| {s['id']} | {tc(s['output_start_frame'])} | "
                f"{tc(s['source_start_frame'])}–{tc(s['source_end_frame'])} | "
                f"{s['text']} | {s['reason']} |\n")

print(f'{len(segs)} segments, {tc(out)} total. Read plan.md before rendering anything.')
